kili-technology/kili-python-sdk

kili/queries/lock/__init__.py
=> Mark locks query resolvers as compatible with v2

kili/helpers.py, kili/mutations/label/__init__.py, kili/playground.py
=> AAU, on API, when I use a method using asset_id as parameter, I see it also accepts external_id

kili/mutations/project/__init__.py, kili/mutations/project/queries.py
=> Keep internal method "__delete_project" for internal use by Kili

README.md
This PR updates the instructions to instantiate the Kili client, by adding the case when the API_KEY is passed through the environment. This capability is already present in the `master` branch: https://github.com/kili-technology/kili-playground/blob/e7430bb8a79cc4932b5f68e671598ae9dc81b274/kili/client.py#L56
=> AAU on Kili, when I set up KILI_API_KEY, I see it I can directly use kili = Kili()

.github/workflows/ci.yml, kili/queries/asset/__init__.py, kili/utils.py, test/queries/test_asset.py
**Overview**
This PR handles the asset pagination through a generator.  Additionally, when `as_generator` is passed as an argument, it outputs a generator of the asset samples. 
It also fixes the following issue: when the `first` argument was passed, it was not using pagination internally and was calling the API directly with the `first` parameter (making it crash if too high)
**Code changes**
* changed `.assets` method in `kili.queries.asset`
* added a `row_generator_from_paginated_calls` which can be used across the board to paginate the other row types.
**Test**
Added a unit test for the `.assets` method by mocking the calls to the API. Also tested locally by calling the API.
**Side effects**
May break the usage of assets everywhere, low risk since it has been tested.
=> feat(ML-27): handle paginated queries inside .assets method

kili/queries/asset/__init__.py, kili/queries/issue/__init__.py, kili/queries/label/__init__.py, kili/queries/lock/__init__.py, kili/queries/notification/__init__.py, kili/queries/organization/__init__.py, kili/queries/project/__init__.py, kili/queries/project_user/__init__.py, kili/queries/project_version/__init__.py, kili/queries/user/__init__.py
=> AAU, on playground, when I query objects, they are returned as a list by default and I don't see warnings anymore

kili/mutations/label/__init__.py
=> AAKD, on playground, when I kili.create_predictions with no prediction (empty list), I see an explicit warning message

kili/queries/project_version/__init__.py
This was happening because the `project` field is no longer allowed.
=> fix(ML-558): rm project from the fields in proj. version query

kili/exceptions.py, kili/helpers.py, kili/utils/pagination.py
first step to clean up errors in the SDK: get rid of the stack trace coming from the backend, and only keep the message.
=> feat: clean the exception strings

kili/cli/project/__init__.py, kili/cli/project/list_.py, kili/cli/project/member/__init__.py, kili/cli/project/member/list_.py, test/cli/test_project.py
few remarks: 
- I put the Organization name because I think it is interesting but I did not put organization role (ADMIN or USER), wdyt?
- I kept the role_id (or project_user_id) as we put it in the specs, but actually, I am for removing it: even in the labeling authors, the user_id is used and not the project_user_id (the only use I can find is for the delete_user mutation). wdyt?
=> AAU, on the CLI, I see a function to list all members of a project

.github/workflows/daily.yml
The following notif is sent to the #python-sdk channel
=> chore: send slack message if SDK test failure

kili/authentication.py, kili/cli/helpers.py, kili/cli/project/__init__.py, kili/cli/project/export.py, kili/project/__init__.py, kili/services/__init__.py, kili/services/export/exceptions.py, kili/services/export/format/base.py, kili/services/export/format/yolo/__init__.py, kili/services/export/format/yolo/common.py, kili/services/export/format/yolo/merge.py, kili/services/export/format/yolo/split.py, kili/services/export/repository.py, kili/services/export/tools.py, kili/services/export/typing.py, recipes/ocr_pre_annotations.ipynb, test/cli/test_project.py, test/services/export/expected/classes.txt, test/services/export/expected/data.yaml, test/services/export/fakes/fake_content_repository.py, test/services/export/fakes/fake_data.py, test/services/export/fakes/fake_kili.py, test/services/export/test_export.py
This PR adds the export feature to the CLI and the SDK. The Yolo formats have been implemented for now.
This is more or less a copy-paste of the code of `label-export`, with the following modifications:
* removal of the web-specific code
* change of the enum types to literal (more convenient for the end-user)
* `YoloExporterSelector` handles the exporter selection (split or merged layout) and initializes the dependencies. This is not a proper dependency injection, this will be done later.
* `YoloSplitExporter` and `YoloMergedExporter` handle the export operations and common code is factorized in the parent class.
* `ContentRepository` objects handle fetching the assets from the backend.
* A service layer has been added to handle the calls from the Python client through `project` and the …
=> Yolo export in CLI and SDK

kili/cli/project/label.py, kili/graphql/operations/asset/mutations.py, test/cli/test_project.py
I don't really know why `"label_asset_id": None` is now output when `label_asset_external_id` is called, but that fixes the issue.
=> fix: asset import cli call

kili/services/asset_import/base.py, kili/services/export/format/yolo/common.py, kili/services/label_import/importer/__init__.py, kili/utils/pagination.py, kili/utils/tqdm.py
Checked locally that the warning is not there anymore.
=> chore: unify tqdm across the client

entrypoint.sh
we don't want to pull the master branch into a release branch
=> build: remove the pull from the master branch

.github/workflows/e2e_tests.yml
Two notebooks fail because they currently cannot run on Windows: https://github.com/kili-technology/kili-python-sdk/actions/runs/3620652184/jobs/6103126008
I had to modify the pytest command since glob patterns don't seem to be working on Windows.
=> test: add e2e tests for windows

src/kili/services/export/format/coco/__init__.py, tests/services/export/expected/car_1_without_annotation.xml, tests/services/export/fakes/fake_data.py, tests/services/export/test_coco.py, tests/services/export/test_export.py, tests/services/export/test_voc.py, tests/services/export/test_yolo.py
- tests: added failing test for COCO export when no annotations
- tests: added failing test for COCO export when no annotations
- tests: Yolo without annotations
- tests: Pascal VOC without annotations
- tests: file  written in tmp dir
- fix: COCO handles images without annotations
- tests: rm unittest
- fix: pyright
=> fix: export COCO labels with no annotations

src/kili/mutations/asset/__init__.py, src/kili/mutations/asset/helpers.py, src/kili/mutations/helpers.py, src/kili/mutations/label/__init__.py, src/kili/queries/label/__init__.py, src/kili/services/helpers.py, tests/e2e/test_mutations_asset.py
TODO:
For `update_properties_in_assets`, if both `external_ids` and `asset_ids` are provided, it raises and says we can't provide both anymore.
=> feat: add external ids parameter to methods

src/kili/types.py
@Jonas1312 Here is the cause.
When executing the mutation, it returns a Project. Then we query the new project to have the fields changed.
When a user ask for fields to query, we compare it the the object type define in kili/types to warn him if he asks a wrong field and do not launch the query to the backend. Here we just didn't add the metadataTypes in the Project Type so the query is refused.
This error is new because the fact that we do a query in update_properties_in_project is new
=> fix: add metadataType in Project type

.github/workflows/ci.yml
python 3.11 tests take more than 4 minutes sometimes: https://github.com/kili-technology/kili-python-sdk/actions/runs/3872411293
=> ci: increase timeout for unit tests

.github/workflows/e2e_tests.yml
e2e tests on windows take a bit longer:
- https://github.com/kili-technology/kili-python-sdk/actions/runs/3874197594/jobs/6605106175
- https://github.com/kili-technology/kili-python-sdk/actions/runs/3873949154/jobs/6604567448
=> ci: increase timeout for e2e tests

.pre-commit-config.yaml, docs/utils.py
new pre commit hooks:
- one for checking if notebook is formatted with black (only applies to notebooks in `/docs/sdk/tutorials`)
- another one that triggers during commit when notebook or markdown files are modified in `/docs/sdk/tutorials`. The hook will check if the notebook is up-to-date with the markdown generated file. It will also check if the markdown is present in `mkdocs.yml`
One command `python -m docs.utils convert tuto.ipynb` to convert `tuto.ipynb` notebook to markdown `tuto.md`.
Images are included in the markdown directly as base64 blobs.
=> docs: add tool to convert notebook to markdown

src/kili/services/export/__init__.py
```python
kili.export_labels("clcrqd3sl0ajz0lnbc3tt43nf", "export_coco.zip", fmt="coco")
```
gives: `AttributeError: 'GraphQLClient' object has no attribute 'auth'`
`get_project` expects `kili` but got `kili.auth.client`
```python
def get_project(kili, project_id: str, fields: List[str]):
"""Get a project from its id or raise a NotFound Error if not found"""
projects = cast(
List[Dict],
ProjectQuery(kili.auth.client)(  # CRASH HERE
ProjectWhere(project_id=project_id), fields, QueryOptions(disable_tqdm=True)
),
)
if len(projects) == 0:
raise NotFound(
f"project ID: {project_id}. Maybe your KILI_API_KEY does not belong to a member of the"
" project."
)
return projects[0]
```
=> fix: fix bug in `export_labels`

.github/workflows/ci.yml, src/kili/services/export/format/base.py, src/kili/services/export/format/coco/__init__.py, src/kili/services/label_import/parser/__init__.py, tests/cli/project/test_project.py, tests/cli/project/test_project_member.py, tests/services/export/test_export.py, tests/services/export/test_yolo.py, tests/services/import_labels/test_import_from_files.py, tests/test_client.py, tests/utils.py
Windows specificities:
- `requests.get()` needs `os.environ` keys, be careful when mocking
- always create the directory before moving/copying/creating a file into it
- use `os.sep` to get the windows `\\` or unix `/` separators
- `csv.writer` requires a file object with `newline=""` : https://stackoverflow.com/questions/3191528/csv-in-python-adding-an-extra-carriage-return-on-windows
- sometimes `print()` fails to encode characters when windows cmd is set to CP-1252 encoding
TODO:
=> test: fix windows unit testing

.github/workflows/publish.yml, .github/workflows/release_draft_minor.yml, .github/workflows/release_draft_patch.yml, entrypoint.sh
- `publish.yml`:
- remove `--reviewer` since `GH_TOKEN` needs specific rights to assign reviewers...
- `release_draft_minor.yml`
-  the variable `link_to_draft` set from `$(./entrypoint.sh release:draft ${{ inputs.releaseVersion }})` had an extra line before the link. We filter the link with grep
- `release_draft_patch.yml`
- I also added the grep filtering just to be sure, even though it worked well last time: https://github.com/kili-technology/kili-python-sdk/actions/workflows/release_draft_patch.yml
- `entrypoint.sh`
- the last tag on master branch is 2.123.2. Thus, github always generates the changelogs based on this tag. We now pass `--notes-start-tag` that fetches the latest release version
=> ci: fix bugs in ci

.github/workflows/deploy_doc.yml, .github/workflows/publish.yml
new deploy_doc.yml workflow:
- runs on workflow_dispatch to be able to trigger it manually
- runs on workflow_call to allow it being called by publish.yml
- I am not sure that the deploy_doc.yml will checkout the repository on the release branch. So I added a step to get the latest release version, and I checkout the proper release branch
in publish.yml
- removed the doc deployment related code
- calls the deploy_doc.yml workflow when the `publish` job is finished, whether it succeeded or not
=> ci: add ci for deploying doc

.github/workflows/ci.yml, .github/workflows/e2e_tests.yml
- -r flag can be used to display a “short test summary info”. -a to not show passed tests
- -sv (-s to disable capturing stdout, -v for verbose mode)
- -vv to increase verbosity
- --durations=15 to get the 15 slowest tests
=> ci: make pytest more verbose

.github/workflows/ci.yml
Use this link checker: https://github.com/lycheeverse/lychee
I had to exclude `--exclude '^(http|https)://cloud.kili-technology.com/api/label/v2/graphql$'`  since it returns a http 400 error code
runs in 15s: https://github.com/kili-technology/kili-python-sdk/actions/runs/3986198229/jobs/6834486502
=> ci: fix markdown link checker

.pylintrc
disable should appear only once in the config file:
> put this option multiple times (only on the command line, not in the configuration file where it should appear only once).
=> style: fix .pylintrc

.github/workflows/e2e_tests.yml
we should consider removing some notebook tests maybe?  Or we can run them just once a day with a cron?
wdyt @kili-technology/ml ?
e2e tests: (~7min)
```
============================= slowest 15 durations =============================
114.50s setup    tests/e2e/test_query_assets_download_media.py::test_download_single_asset_big_image
63.05s call     tests/e2e/test_copy_project.py::test_copy_project_e2e
31.59s setup    tests/e2e/test_copy_project.py::test_copy_project_e2e
23.66s setup    tests/e2e/test_query_assets_download_media.py::test_download_single_asset_video_content_and_jsoncontent
22.15s setup    tests/e2e/test_mutations_asset.py::test_add_to_review
11.59s setup    tests/e2e/test_mutations_asset.py::test_send_back_to_queue
10.78s setup …
```
=> ci: do not run notebook tests for merge on master

.github/workflows/e2e_tests.yml
we expect the user to check if they passed or not
=> ci: remove slack notification for e2e tests ran manually

.pre-commit-config.yaml, docs/sdk/tutorials/export_a_kili_project.md, docs/sdk/tutorials/importing_assets_and_labels.md, docs/sdk/tutorials/importing_video_assets.md, docs/sdk/tutorials/plugins_development.md, docs/sdk/tutorials/plugins_example.md, docs/sdk/tutorials/set_up_workflows.md, recipes/counterfactual_data_augmentation.ipynb, recipes/export_a_kili_project.ipynb, recipes/importing_assets_and_labels.ipynb, recipes/importing_video_assets.ipynb, recipes/medical_imaging.ipynb, recipes/plugins_development.ipynb, recipes/plugins_example.ipynb, recipes/set_up_workflows.ipynb
force upgrading kili via pip breaks the test environment (if we want to test earlier version of kili sdk)
also add another precommit for cleaning notebooks, the precommit "nb-clean" does not clean everything unfortunately
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4026700002
=> docs: stop forcing kili upgrade in notebooks

.github/workflows/precommit.yml, .pre-commit-config.yaml
isort pre-commit hook had some incompatibilities with python3.7: https://github.com/PyCQA/isort/issues/2083
=> ci: fix pre-commit ci

src/kili/types.py
solves:
```bash
NonExistingFieldError: Cannot query field maxNumberOfAnnotationsPerMonth on object License. Admissible fields are: 
- api
- apiPriority
- canUsePlugins
- enableSmartTools
- expiryDate
- inputType
- maxNumberOfLabeledAssets
- seats
- startDate
- type
- uploadCloudData
- uploadLocalData
- organizationId
```
```graphql
type License {
_: Boolean
api: Boolean
apiPriority: Boolean
canUsePlugins: Boolean
enableSmartTools: Boolean
expiryDate: String
inputType: [String!]
maxNumberOfAnnotations: Int
maxNumberOfAnnotationsPerMonth: Int
maxNumberOfLabeledAssets: Int
maxNumberOfLabeledAssetsPerMonth: Int @deprecated(reason: "This is not part of the billing")
maxNumberOfPredictionsPerMonth: Int
organizationId: String
seats: Int
startDate: String
type: LicenseType
uploadCloudData: …
```
=> fix: fix GraphQL types for License

src/kili/queries/asset/media_downloader.py, src/kili/services/copy_project/__init__.py, src/kili/services/export/format/kili/__init__.py
```python
kili.export_labels(
project_id=PROJECT_ID,
filename="./kili_export.zip",
fmt="coco",
single_file=True,
)
```
```
Fetching assets...
0%|                                                                                                                                                                                                                                               | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
File "/Users/brice/mltwist/testing/getAnnotations.py", line 50, in <module>
kili.export_labels(
File "/Users/brice/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/kili/queries/label/__init__.py", line 312, in export_labels
services.export_labels(
File "/Users/brice/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/kili/services/export/__ini …
```
=> fix: fix export bug when jsonContent is None

src/kili/queries/asset/__init__.py, src/kili/queries/asset/media_downloader.py, src/kili/services/copy_project/__init__.py, src/kili/services/export/tools.py
the ProjectQuery was using fields for AssetsQuery
the assets copy in ProjectCopier was not done
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4075049946
=> fix: fix bugs in ProjectCopier and MedialDownloader

.github/scripts/utils.sh, .github/workflows/bump_commit_release_branch.yml
version `002129001` will be interpreted as base 00. We force base 10 conversion
tests:
```bash
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ source ./.github/scripts/utils.sh
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ echo $(version_to_int 2.129.1)
2129001
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ echo $(version_to_int "2.129.1")
2129001
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ echo $(version_to_int "2.129.145")
2129145
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ echo $(version_to_int "442.129.145")
442129145
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗ echo $(version_to_int "002.129.145")
2129145
(python37) ➜  kili-python-sdk git:(ci/fix-ci-workflows) ✗
```
=> ci: fix bug in utils.sh script

src/kili/mutations/asset/__init__.py, src/kili/mutations/exceptions.py, src/kili/mutations/project/__init__.py, src/kili/services/asset_import/base.py, src/kili/services/asset_import/exceptions.py, src/kili/services/asset_import/types.py, src/kili/services/asset_import/video.py, src/kili/services/label_import/importer/__init__.py, src/kili/utils/pagination.py, tests/e2e/test_mutations_asset.py, tests/services/asset_import/test_import_common.py, tests/services/asset_import/test_import_image.py, tests/services/asset_import/test_import_pdf.py, tests/services/asset_import/test_import_text.py, tests/services/asset_import/test_import_video.py, tests/test_pagination.py
I looked at past failed e2e tests and added:
- `append_many_to_dataset`: verify that last batch is uploaded in `BaseBatchImporter.import_batch` by querying assets every second for 5s
- `create_project`: check that project is created every second during 5s
- `send_back_to_queue`, `add_to_review` and `delete_many_from_dataset`: add a callback in `_mutate_from_paginated_call` that checks the last batch
For other asset mutations, `update_properties_in_assets` and `change_asset_external_ids`, I cannot query the assets since the project id is not available in those methods, but required in `AssetWhere`. The simplest thing we can do is add a small delay at the end of `_mutate_from_paginated_call` I think
=> fix: add delay after mutations

.github/workflows/e2e_tests_previous_release.yml
ML-971
pip install kili from git master
then checkout repo from latest release branch and run tests
useful to make sure we don't introduce BC in master branch compared to the lastest release
not tested yet
=> ci: add CI to run tests from prev release against master

.github/workflows/bump_commit_release_branch.yml
in case we forget to delete the previous branch or in case we run the workflow several times, it's safer to create a new branch
tested here: https://github.com/kili-technology/kili-python-sdk/pull/1020
=> ci: make sure bump commit PR branch has unique name

docs/sdk/cloud_storage.md, docs/sdk/remote_storage.md, mkdocs.yml, src/kili/client.py, src/kili/graphql/__init__.py, src/kili/graphql/operations/api_key/queries.py, src/kili/graphql/operations/data_integration/queries.py, src/kili/queries/data_integration/__init__.py
doc rendering is ok
also tested:
```python
kili.data_integrations(platform="Azure", fields=["name", "platform", "status"])
```
returns:
```python
[{'name': 'Test Azure Token based ', 'platform': 'Azure', 'status': 'CONNECTED'}, {'name': 'Test Azure', 'platform': 'Azure', 'status': 'CONNECTED'}, {'name': 'Azure integration for tests', 'platform': 'Azure', 'status': 'DISCONNECTED'}, {'name': 'Test Datalake', 'platform': 'Azure', 'status': 'DISCONNECTED'}, {'name': 'Test demo-container-delegated-access', 'platform': 'Azure', 'status': 'CONNECTED'}, {'name': 'StorageClientAppSample', 'platform': 'Azure', 'status': 'DISCONNECTED'}, {'name': 'test 2', 'platform': 'Azure', 'status': 'CONNECTED'}, {'name': 'test-integration', 'platform': 'Azure', 'status': 'DISCONNECTED'}, {'name': 'test integ …
```
=> feat: add `kili.data_integrations`

src/kili/graphql/operations/data_connection/queries.py, src/kili/graphql/operations/data_integration/queries.py, src/kili/mutations/data_connection/__init__.py, src/kili/queries/data_connection/__init__.py, src/kili/queries/data_integration/__init__.py
I changed integration_id for data_integration_id, since we use data_connection_id 
better include that before release
=> refactor: keep naming consistent with graphql schema

docs/sdk/cloud_storage.md, src/kili/mutations/data_connection/__init__.py, src/kili/queries/data_connection/__init__.py, src/kili/queries/data_integration/__init__.py, src/kili/services/copy_project/__init__.py, src/kili/utils/pagination.py, tests/queries/data_connection/test_data_connection.py, tests/test_pagination.py, tests/utils.py
I had to rework test_pagination.py because pyright CI was not passing because of row_generator_from_paginated_calls method
=> refactor: rename cloud storage methods and update doc

tests/test_notebooks.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4374421316/jobs/7653828732
```shell
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-7.2.2, pluggy-1.0.0 -- /opt/hostedtoolcache/Python/3.7.15/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/kili-python-sdk/kili-python-sdk
plugins: mock-3.10.0, cov-4.0.0, typeguard-2.13.3
collecting ... collected 19 items
tests/test_notebooks.py::test_all_recipes[tests/e2e/create_project.ipynb] PASSED
tests/test_notebooks.py::test_all_recipes[tests/e2e/export_labels.ipynb] PASSED
tests/test_notebooks.py::test_all_recipes[tests/e2e/import_assets.ipynb] PASSED
tests/test_notebooks.py::test_all_recipes[tests/e2e/import_predictions.ipynb] PASSED …
```
=> test: disable tests for plugin notebooks on LTS

tests/e2e/test_copy_project.py
e2e tests for master on LTS: https://github.com/kili-technology/kili-python-sdk/actions/runs/4383296421
the kili.delete_project bug seem to have disappeared
=> test: fix copy project e2e test

src/kili/helpers.py, src/kili/mutations/asset/__init__.py, src/kili/mutations/label/__init__.py, tests/test_helpers.py
add a helperthat raises warning and return bool if the provided input list is empty 
Some methods already check for the len(input_array), so I didn't modify them
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4382202318
=> feat: warn and return if argument of type list is empty

setup.py
should fix e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4424619034
=> fix: restrict typeguard version

setup.py, src/kili/graphql/graphql_client.py, tests/e2e/test_graphql_client.py, tests/graphql/test_graphql_client.py
if the local schema validation fails, we fetch a fresh schema from backend, and retry the query
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4425003433
=> fix: refetch local graphql schema when outdated

src/kili/graphql/graphql_client.py
gql graphql client logs all queries sent which is too verbose by default
```
INFO:gql.transport.requests:>>> {"query": "query projects($where: ProjectWhere!, $first: PageSize!, $skip: Int!) {\n  data: projects(where: $where, first: $first, skip: $skip) {\n    inputType\n  }\n}", "variables": {"where": {"id": "123456", "searchQuery": null, "shouldRelaunchKpiComputation": null, "updatedAtGte": null, "updatedAtLte": null}, "skip": 0, "first": 1}}
INFO:gql.transport.requests:<<< {"data":{"data":[{"inputType":"IMAGE"}]}}
```
=> chore: increase gql logger level

.github/workflows/ci.yml, .github/workflows/e2e_tests.yml, setup.py
use all cpu cores for running tests
2 cores cpus on github infra usually
unit tests:
- windows: 6m54s -> 2m11s
- ubuntu: 5m44s -> 3m40s
e2e (e2e tests + notebooks):
- windows: 22m -> 10m30s
- ubuntu: 24m -> 12m
=> ci: use all cpu cores for pytest

.github/scripts/add_latest_release_branch_to_github_env.py, .github/scripts/utils.sh, .github/workflows/create_draft_release.yml, .github/workflows/e2e_tests.yml, .github/workflows/publish.yml
after creating the branch release/2.130.0, the e2e CI detected the latest branch as being release/2.129.0:
the e2e tests "release branch against preprod" were launched on release/2.129.0, when it should've been launched on release/2.130.0
with this fix:
=> ci: fix bug when fetching last release branch

setup.py, src/kili/core/graphql/graphql_client.py, tests/e2e/test_graphql_client.py
We had this bug several times during the past few days:
```text
E       graphql.error.syntax_error.GraphQLSyntaxError: Syntax Error: Unexpected <EOF>.
E       
E       GraphQL request:1:1
E       1 |
E         | ^
```
this bug would only happen on `test_copy_project_e2e_with_ocr_metadata`
It's hard to reproduce and happens randomly.
Could be caused by writing the schema on disk and reading it just after when the writing is not finished.
Or cause by the fact that we now run tests in parallel. So we can have two kili clients caching the schema at the same time.
=> fix: fix graphql schema caching bug

.github/scripts/add_latest_release_branch_to_github_env.py, .github/workflows/e2e_tests.yml
should solve:
```shell
Run curl https://raw.githubusercontent.com/***/kili-python-sdk/master/.github/scripts/add_latest_release_branch_to_github_env.py --output add_latest_release_branch_to_github_env.py
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1220  100  1220    0     0   8141      0 --:--:-- --:--:-- --:--:--  8243
Traceback (most recent call last):
File "D:\a\kili-python-sdk\kili-python-sdk\add_latest_release_branch_to_github_env.py", line 23, in <module>
response = urllib.request.urlopen(url).read()
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, …
```
=> ci: add retries for script fetching release branches from github

src/kili/client.py, src/kili/core/authentication.py, src/kili/core/graphql/graphql_client.py, src/kili/entrypoints/mutations/label/__init__.py, tests/e2e/test_client.py
done:
- stop storing user id and email in kiliauth saves 100ms
- add an env var `KILI_SDK_SKIP_CHECKS` that disables checks and graphql schema related stuff
`from kili.client import Kili` takes around ~700ms (mostly because of pandas)
`kili = Kili()` takes ~0s when checks are disabled
to consider:
- pandas import takes ~500ms...: It's pretty easy to add lazy loading of import. But I haven't found yet how to type pd.Dataframe 🤔  We can keep it as is for now. Maybe updating to more recent versions of pandas could improve this (we are using old version now because of python3.7)
=> perf: improve Kili client initialization time

src/kili/core/enums.py, src/kili/services/label_data_parsing/json_response.py, src/kili/services/label_data_parsing/label.py, tests/services/label_data_parsing/mutation/test_resp_mutation.py, tests/services/label_data_parsing/parsing/test_resp_parsing.py
purpose of this PR was to switch the `label.frames[42].jobs["job_name"]` to `label.jobs["job_name"].frames[42]`
done:
- removed the project input types that are not in the graphql schema anymore
- in `label.py`, the `ParsedLabel` doesn't have a `.frames` attribute anymore
- in `json_response.py`, the `ParsedJobs` inherits from two private classes `_ParsedOtherJobs` and `_ParsedVideoJobs`, and chooses the right class at runtime depending if the label is a video label or not
- I had to introduce a "fake" class `class JobPayload(FramesList, job_response_module.JobPayload):`. This class is used to expose all attributes/methods of both `FramesList` (for the `.frames` attribute), and all properties of `job_response_module.JobPayload` so that autocompletion works during coding
=> fix: inverse .jobs and .frames order for video label parsing

src/kili/entrypoints/queries/label/__init__.py, src/kili/services/export/exceptions.py, src/kili/services/export/format/base.py, src/kili/services/export/format/coco/__init__.py, src/kili/services/export/format/voc/__init__.py, src/kili/services/export/format/yolo/__init__.py, tests/services/export/test_coco.py, tests/services/export/test_export.py, tests/services/export/test_voc.py
- fix: COCO and VOC exports not possible when data connection
- refactor: isolate asset access test
- tests: fix missing content
- feat: adding specific exception for asset access
- style: pylint and cleanup
- docs: add warning
=> fix: forbid export to COCO and VOC when project is connected to cloud storage

setup.py, src/kili/core/graphql/graphql_client.py
currently, the dependency graphql-core does not fetch all deprecated fields in the graphql schema
see: https://github.com/graphql-python/gql/issues/399
this PR fixes this
e2e tests on staging, preprod and LTS pass
=> fix: fetch deprecated fields of graphql schema

setup.py, tests/e2e/test_client.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4934039946/jobs/8818611523
=> test: add profiling info to client init e2e test

.github/scripts/detect_api_key.py, .pre-commit-config.yaml
Sometimes I put an api key directly in the scripts for running tests, and I almost pushed a branch with an api key on github🙃
the detect-private-key of pre-commit-hooks only detects ssh keys, so I made a simple script to check our kili keys
the regex pattern excludes false positives, especially in jupyter notebook, where cells or attachments have the same unique ids format
=> ci: add pre-commit hook to block kili api keys

src/kili/entrypoints/queries/label/__init__.py
Hava found that it was hard to find the latest label for an asset while using kili.labels
this PR makes the isLatestLabelForUser label field more visible
=> feat: set better default fields for kili.labels()

src/kili/utils/labels/bbox.py, tests/utils/labels/test_bbox.py, tests/utils/labels/test_point.py
currently, the boxes returned by `bbox_points_to_normalized_vertices` are upside down. In other terms, the box is at  the right position, but the rotation handle is at the bottom instead of being at the top of the box.
=> fix: fix box orientation in bbox label utils

.github/workflows/publish.yml
I don't have access to our pypi account
@PierreLeveau you have to follow this tutorial: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
on test pypi account too
=> ci: use pypi trusted publisher

.github/workflows/publish.yml
the "create merge pr" failed yesterday: https://github.com/kili-technology/kili-python-sdk/actions/runs/5466359256/jobs/9951628785
apparently setting the "id-write" permission removes all other permissions
=> ci: fix publish.yml

tests/e2e/test_projects.py
```bash
FAILED tests/e2e/test_projects.py::test_projects_query_archived_project - AssertionError: assert 2 == 3
+  where 2 = len([***'id': 'cljwiufjx004n0j7v5hjr78m0'***, ***'id': 'cljwiuetc004j0j7v08exed7n'***])
+    where [***'id': 'cljwiufjx004n0j7v5hjr78m0'***, ***'id': 'cljwiuetc004j0j7v08exed7n'***] = <bound method QueriesProject.projects of <kili.client.Kili object at 0x00000219D7FB9A90>>(fields=['id'], search_query='8c354ef2-ae64-4cd6-925e-43e3d6fe1065')
+      where <bound method QueriesProject.projects of <kili.client.Kili object at 0x00000219D7FB9A90>> = <kili.client.Kili object at 0x00000219D7FB9A90>.projects
+  and   3 = <bound method QueriesProject.count_projects of <kili.client.Kili object at 0x00000219D7FB9A90>>(search_query='8c354ef2-ae64-4cd6-925e-43e3d6fe1065')
+ …
```
=> test: add delay after mutation to account for replica lag

src/kili/entrypoints/mutations/asset/__init__.py
kili.send_back_to_queue(asset_ids=["blabla"])
would give:
```
File "/Users/jonasm/kili-python-sdk/src/kili/entrypoints/mutations/asset/__init__.py", line 567, in send_back_to_queue
results = mutate_from_paginated_call(
File "/Users/jonasm/kili-python-sdk/src/kili/core/utils/pagination.py", line 116, in mutate_from_paginated_call
last_batch_callback(batch, results)
File "/opt/anaconda3/envs/python38/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
return self(f, *args, **kw)
File "/opt/anaconda3/envs/python38/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
do = self.iter(retry_state=retry_state)
File "/opt/anaconda3/envs/python38/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
return fut.result()
File …
```
=> fix: fix bug when no data is returned

src/kili/core/graphql/graphql_client.py, tests/unit/test_graphql_client.py
It's not a perfect solution, since the `variables` can be a nested dict.
Also, some inputs could have a non-nullable JSON type (`metadata: JSON!`), and in that case, if we pass `variables = {"metadata": {"truc": None}}` we don't want to remove the child dict.
e2e pass, so I think it's a good enough solution: https://github.com/kili-technology/kili-python-sdk/actions/runs/6349198396
=> fix: remove null from variables in gql query

src/kili/presentation/client/internal.py
useful for the mutations, that have not been migrated yet towards the new archi
=> fix: missing graphql client init for internal methods

src/kili/adapters/kili_api_gateway/label/common.py
FAILED tests/e2e/test_copy_project.py::test_copy_project_e2e_video - kili.exceptions.GraphQLError: GraphQL error: "Cannot query field 'job' on type 'Annotation'."
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/6823160395
=> fix: don't query annotations resolver on LTS

src/kili/services/export/format/base.py, src/kili/services/export/format/geojson/__init__.py, src/kili/services/export/format/kili/__init__.py, src/kili/services/export/format/voc/__init__.py, src/kili/services/export/format/yolo/__init__.py, tests/unit/services/export/helpers/coco.py, tests/unit/services/export/test_geojson.py, tests/unit/services/export/test_kili.py, tests/unit/services/export/test_voc.py, tests/unit/services/export/test_yolo.py
for example, `as/set.png` will be exported as : 
- labels/
- as /
- set.png
=> fix: fix export when an asset has a slash

.github/workflows/e2e_tests.yml
LTS instances start on demand, so they might be off when test triggers.
=> test: remove cron triggers on e2e tests on LTS instances

src/kili/adapters/kili_api_gateway/cloud_storage/mappers.py, src/kili/adapters/kili_api_gateway/cloud_storage/types.py, src/kili/use_cases/cloud_storage/__init__.py, src/kili/use_cases/cloud_storage/azure.py, tests/integration/adapters/kili_api_gateway/test_cloud_storage.py
This MR should not be merged yet, we must wait for the contentTypes parameter to be added in the computeDifferences mutation of the API.
=> feat(lab-2616): add contentTypes to compute dataConnection differences

docs/sdk/tutorials/inference_labels.md, recipes/inference_labels.ipynb
The computation of inference, honeypot and reviewScore are now compute asynchronously so we need to wait for the data to be compute in the test.
=> fix(LAB-2676): add sleep for wait for inference in notebook

src/kili/adapters/kili_api_gateway/asset/formatters.py, src/kili/adapters/kili_api_gateway/label/formatters.py, src/kili/adapters/kili_api_gateway/project/formatters.py, src/kili/services/copy_project/__init__.py
In some cases, backend may return an empty string when having no values for jsonMetdata. In order to avoid blocking errors when backend return an invalid or empty json field, we consider the field as not set.
=> fix: ignore json loads errors

src/kili/adapters/kili_api_gateway/asset/mappers.py
Querying with a lot of partial external id is costly for database.
In next releases, we will limit this search. We add a warning in the meantime.
---
=> chore(lab-2851): add a warning when trying to filter by more than 10+ partial external id

src/kili/services/asset_import/base.py, src/kili/services/asset_import/video.py, tests/unit/services/asset_import/test_import_video.py
This MR adds : 
- Async import management for all videos (NATIVE_VIDEO and FRAME_VIDEO)
- adds a limit (5 min) to wait for imported assets in case of async imports
=> feat(LAB-2828): manage native video imports asynchronously

src/kili/services/asset_import/exceptions.py, src/kili/services/asset_import/helpers.py, src/kili/services/asset_import/llm.py, tests/unit/services/asset_import/test_import_llm.py
- Adds file data conversion from chat (Mistral) format (if present) to our asset content format
- Adds jsonMetadata for the following keys : 
- chat_id
- chat_item_ids
- models
- text (for asset interface display) : with chat_id and chat_item_ids
- Adds 3 tests : 
- one for uploading a file in chat format without jsonMetadata
- one for uploading a file in chat format with jsonMetadata
- one for unit testing the processJson method which converts the chat format file data into llm kili format asset data
=> feat(LAB-2944): add file data conversion prior to import for new llm format

src/kili/services/asset_import/helpers.py
This MR changes the parsing of the payload to use the role key to identify if the prompt is a model or user prompt : the user prompt has a "role" that is either "user" or "system".
Tested it on the EU Prod project : https://cloud.kili-technology.com/label/projects/clxt6xtd42rac015rhxtb9kpz/menu/queue?disableVersion=1
Import works, export -> import works as well.
=> feat(LAB-2944): identify user prompt with role key

pyproject.toml, src/kili/services/export/format/coco/__init__.py
Currently it contains the area of the image instead of the area of the annotation and some annotations are exported with null dimensions.
=> fix(lab-2558): fix area property of COCO export and ignore empty bboxes

src/kili/llm/services/export/dynamic.py, tests/unit/llm/services/export/test_dynamic.py
Remove the field name from assetProjectModels query as it does not exist anymore in the API.
The name of the model that really matters for the user is still returned in the export.
=> feat: remove name from assetProjectModels query

src/kili/services/export/format/kili/__init__.py
Calling Path with a dict raise an error on python versions before 3.12
=> fix(lab-3323): fix export for geosat projects

src/kili/services/label_data_parsing/job_response.py
Exports in the format `parsed_label` failed when multiple jobs in the interface referenced the same child classification job. The same child classification job categories dict was casted to a CategoryList multiple times which failed.
=> fix(sup-1998): only cast CategoryList once per job

src/kili/core/constants.py, src/kili/domain/project.py, src/kili/services/asset_import/__init__.py, src/kili/services/asset_import/base.py, src/kili/services/asset_import/image.py, src/kili/services/asset_import/llm.py, src/kili/services/asset_import/pdf.py, src/kili/services/asset_import/text.py, src/kili/services/asset_import/video.py, tests/integration/adapters/kili_api_gateway/test_paginated_graphql_query.py, tests/manual/geospatial_import_tests.py
You can try to import geospatial assets using this [manual tests](https://github.com/kili-technology/kili-python-sdk/pull/1863/files#diff-85d208e5edf625ab844d2a18ff3265433b06932ed81ac0014f975b8f142c1647) (automatically download & import various geotiffs) or use this snippet :
```
from kili.client import Kili
from scripts.constants import LOCAL_KILI_API_KEY
kili = Kili(api_key=LOCAL_KILI_API_KEY, api_endpoint='http://localhost:4001/api/label/v2/graphql', verify=False)
projects = kili.projects()
for project in projects:
if project['inputType'] == 'GEOSPATIAL':
kili.delete_project(project['id'])
JSON_INTERFACE = {
"jobs": {
"JOB_0": {
"mlTask": "CLASSIFICATION",
"required": 1,
"isChild": False,
"content": {
"categories": {"OBJECT_A": {"name": "Object A"}, "OBJECT_B": {"name": "Object B"}}, …
```
=> feat(LAB-3459): add missing code to import geospatial image through SDK

src/kili/entrypoints/mutations/asset/__init__.py, tests/integration/presentation/test_metadata.py
Previously, we could only add/set metadata using asset_id
This MR add ability to use external_ids
```
kili.add_metadata([{'foo': 'bar'}], external_ids=['hd_video.mp4'], project_id="cm9wi5b1b00e3x30w04mh6g5q")
```
=> fix(LAB-3532): handle `external_ids` arg for `add_metadata` and `set_metadata`

pyproject.toml, src/kili/presentation/client/label.py, src/kili/use_cases/label/process_shapefiles.py, tests/unit/utils/labels/test_shapefiles.py
- Added support for correctly handling different job types (marker, polyline, rectangle, polygon, semantic)
The previous implementation only correctly handled `semantic` job type. This MR adds proper support for building correct `json_response` for all job type, using project `json_interface`
- Fixed issue with duplicate coordinates in QGIS-exported shapefiles
_Shapefiles from QGIS often "close" annotations, resulting in duplicate coordinates (e.g., first and last points are identical in polygons). This MR removes these duplicate points to ensure valid annotations._
=> feat(LAB-3634): refactor shapefile import using project json_interface
