kili-technology/kili-python-sdk

- kili/__init__.py
- kili/authentication.py
- kili/queries/asset.py
Reverts kili-technology/kili-playground#67
> Revert "Fixed version for {"version": "0.1.2"}"

- kili/mutations/asset.py
- kili/mutations/project.py
- kili/mutations/tool.py
- kili/queries/asset.py
- kili/queries/tool.py
Reverts kili-technology/kili-playground#79
> Revert "Feature/aa kili dev in seed.iv1.graphql i see a better seed with iv1 projects"

- kili/mutations/asset.py
- kili/mutations/project.py
- kili/mutations/tool.py
- kili/queries/asset.py
- kili/queries/tool.py
Reverts kili-technology/kili-playground#80
> Revert "Revert "Feature/aa kili dev in seed.iv1.graphql i see a better seed with iv1 projects""

- kili/mutations/label.py
- kili/mutations/user.py
- kili/playground.py
Fix of update proprerties in label
> Added update proprerties in user

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/playground.py
AAU, on kili-playground, I don't see create_project
> AAU, on kili-playground, I don't see create_project

- kili/queries/project/__init__.py
- kili/queries/project/queries.py
Co-authored-by: Pierre Marcenac <marcenacp@users.noreply.github.com>
> Add a count_projects resolver

- kili/types.py
> Added new calculated fields

- kili/queries/asset/__init__.py
- kili/queries/asset/queries.py
Reverts kili-technology/kili-playground#165
> Revert "Feature/3292 8 aa kd when i look at relation resolvers assetlabels i see it uses a where argument to filter out autosaves"

- kili/graphql_client.py
> Raise errors (instead of printing)

- kili/__init__.py
> Bump to version 2.0.7

- kili/types.py
> AA serviceaccount, on project SmartReno, on my laptop, when I go to dataset/asset, I see my data in less than 5s

- kili/authentication.py
- kili/graphql_client.py
> Verify SSL can be true or false

- recipes/transfer_learning_with_yolo.ipynb
> AAKD, on playground, when I launch tests, I see a success

- kili/authentication.py
> Add a deprecation message on authentication without an API key

- kili/authentication.py
- [ x] I opened a merge request on `kili` on a branch with the same name than the branch of the current pull request
> Make all warnings visible by default

- .travis.yml
- recipes/import_assets.ipynb
> Precise doc on import assets and make it a tested recipe.

- kili/__init__.py
> Bump version to 2.2.0 for next production release

- kili/authentication.py
> Remove numpy warnings

- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
> AAU, on video, when I upload a file, I see it loaded

- kili/__init__.py
> Bump to version 2.3.0

- kili/mutations/notification/__init__.py
- kili/mutations/notification/fragments.py
- kili/mutations/notification/queries.py
- kili/playground.py
> Manage notifications (creation/update)

- kili/types.py
> Add cross-referenced types (like Asset <> Label)

- kili/__init__.py
> Bump version to 2.3.3

- kili/__init__.py
> Bump version to 2.4.0

- kili/authentication.py
> Remove deprecated functions in kili-playground

- kili/__init__.py
> Bump to version 2.5.0

- kili/mutations/notification/__init__.py
- kili/mutations/notification/queries.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
> AAU, when I delete a project, I see a notification when finished

- kili/__init__.py
> Bump to version 2.7.0

- kili/authentication.py
- recipes/README.md
- recipes/add_users.py
- recipes/delete_all_assets.py
- recipes/get_labeler_stats.py
- recipes/google_ner_pre_labeling.py
> Improve doc on graphql playground

- kili/__init__.py
> Bump to version 2.8.0

- .travis.yml
- kili/authentication.py
- recipes/README.md
- recipes/active-learning/active_learning.ipynb
- recipes/automl_text_classification.ipynb
- recipes/counterfactual_data_augmentation.ipynb
- recipes/create_project.ipynb
- recipes/get_labeler_stats.py
- recipes/import_assets.ipynb
- recipes/import_predictions.ipynb
- recipes/medical_imaging.ipynb
- recipes/set_asset_to_be_labeled_by.py
- recipes/transfer_learning_with_yolo.ipynb
- recipes/update_project_instructions.py
- recipes/update_project_title.py
- recipes/webhooks.ipynb
> Migrate from label-backend to label-backend-v1

- kili/__init__.py
> Bump to version 2.9.0

- kili/authentication.py
- [ x] I opened a merge request on `kili` on a branch with the same name than the branch of the current pull request
> Improve handling of version check with try catch

- kili/__init__.py
> Bump to version 2.11.0

- kili/__init__.py
> Bump to version 2.12.1

- kili/mutations/project/__init__.py
- kili/queries/project/__init__.py
- kili/types.py
> AAU, when I update quality settings, I see all calculated field updated

- kili/__init__.py
> Bump version to 2.13.0

- kili/__init__.py
> Bump version

- kili/helpers.py
- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
- kili/mutations/notification/__init__.py
- kili/mutations/organization/__init__.py
- kili/mutations/project/__init__.py
- kili/mutations/user/__init__.py
- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
- kili/queries/lock/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/user/__init__.py
> Add decorator to methods to precise on which backend they can run

- kili/helpers.py
- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
> AAU VitadX, when I modify assets, I can do it by batch

- kili/mutations/asset/__init__.py
> Add Compatible on delete_many_from_dataset

- kili/graphql_client.py
- kili/subscriptions/label/__init__.py
> AAU, on playground, when I use webhooks, I understand why they are slow

- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
> Make label queries usable with v2

- kili/__init__.py
> Bump version to 2.16.0

- kili/__init__.py
> update version to 2.17.0

- kili/__init__.py
> Add new version 2.18.0

- kili/mutations/user/__init__.py
- kili/mutations/user/queries.py
> AAU, on Playground, When I use create_user_from_email_if_not_exists, I see a success

- recipes/webhooks.ipynb
> AAU, I see the doc on webhook is updated

- kili/__init__.py
> Bump version to 2.19.0

- kili/__init__.py
> Bump to version 2.19.0

- kili/mutations/user/__init__.py
- kili/mutations/user/queries.py
> AAU, on playground v2, when I use mutations, I see a success [USER]

- kili/graphql_client.py
> AA U, I can use the webhooks extensively

- kili/mutations/user/__init__.py
> Deprecate create_user_from_email_if_not_exist

- kili/__init__.py
> Update to version 2.22.0

- kili/mutations/asset/__init__.py
> Add v2 support for delete_many_from_dataset / append_many_to_dataset

- kili/mutations/label/__init__.py
> Activate mutations for label in v2

- kili/__init__.py
> bump-version-2.23.0

- kili/mutations/notification/__init__.py
> Unable V2 on create/update notifications

- kili/__init__.py
> Bump version to 2.25

- kili/__init__.py
> Bump version to 2.26

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/types.py
- recipes/conf/new_project.yml
> AAU, on playground v2, when I use mutations, I see a success [PROJECT]

- kili/helpers.py
- kili/mutations/asset/__init__.py
> Import URL in jsonContent without dumping it

- kili/mutations/user/__init__.py
> Implement AA KD, on kili-playground, I don't see deprecated methods

- kili/graphql_client.py
- recipes/README.md
- recipes/import_text_assets.ipynb
> AAU, on code/recipe/doc, I don't see any reference to /v1/playground

- kili/helpers.py
- kili/mutations/asset/__init__.py
> AAU, on schema, when I open a Schema, I see a directive hasSomeRole implemented

- kili/mutations/organization/__init__.py
> AA KD, on https://docs.google.com/spreadsheets I see all implemented queries/mutations are used in frontend

- kili/__init__.py
> Bump to version 2.27

- kili/__init__.py
> Bump to version 2.28.0

- kili/__init__.py
- pull_request_template.md
> Bump to 2.29. and release

- kili/__init__.py
> Bump to version 2.31

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- recipes/import_text_assets.ipynb
> Add new method: make_project_public

- kili/__init__.py
> Bump to version 2.32.0

- kili/queries/organization/__init__.py
- kili/queries/organization/queries.py
- kili/types.py
> Added countOrganizations

- kili/__init__.py
> Bump to version 2.33.0

- kili/mutations/organization/__init__.py
- kili/mutations/organization/queries.py
> AA Freemium U, when I use the API, I see an error message

- kili/authentication.py
> Update default endpoint for v1 deprecation

- kili/types.py
> Add numberOfAnnotations calculated field to organization

- recipes/import_text_assets.ipynb
> Fix recipe import text assets

- kili/queries/project_user/__init__.py
- kili/queries/project_user/queries.py
> Added countProjectUsers

- kili/mutations/asset/__init__.py
> Decorate method "update_properties_in_asset"

- recipes/import_text_assets.ipynb
> Copy dictionary to avoid modifying its reference

- kili/__init__.py
> Bump version 2.36

- kili/__init__.py
> Bump to 2.37

- kili/__init__.py
> Bump to version 2.38.0

- kili/__init__.py
> Bump to version 2.39.0

- .travis.yml
- kili/helpers.py
- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
- kili/orm.py
- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
- recipes/export_labels.ipynb
> Add an ORM to manipulate Kili objects

- kili/__init__.py
> Bump to version 40

- kili/types.py
> Add calculated field

- kili/__init__.py
> Bump to version 2.41.0

- recipes/getting-started/getting_started-classification.ipynb
> Fix title of getting started recipe

- kili/__init__.py
> Bump version to 2.42

- kili/types.py
> New resolver

- kili/types.py
> Add Issues type and CommentsWithoutCommentsOf

- kili/__init__.py
> Bump to v44

- kili/__init__.py
> Change version

- kili/__init__.py
> Bump to version 2.46.0

- kili/helpers.py
- kili/mutations/asset/__init__.py
> Add support to push pdf raw content and Frame jsonContent as URL through the API

- kili/__init__.py
> Bump version to 2.47

- kili/helpers.py
> AAU, on playground, when I query assets, I see I can query the assets metadata

- kili/__init__.py
> Bump to v.48

- kili/graphql_client.py
- kili/subscriptions/label/__init__.py
- recipes/webhooks.ipynb
> Fix for webhooks : function definition and documentation

- kili/types.py
> Add review coverage field to project model

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/queries/project/__init__.py
- kili/types.py
Reverts kili-technology/kili-playground#321
> Revert "review coverage"

- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
- kili/mutations/notification/__init__.py
- kili/mutations/organization/__init__.py
- kili/mutations/project/__init__.py
- kili/mutations/user/__init__.py
- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
- kili/queries/lock/__init__.py
- kili/queries/notification/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/user/__init__.py
- kili/subscriptions/label/__init__.py
- setup.py
> AA DS, on kili-playground, I see strong typing

- kili/__init__.py
> Bump to v50

- kili/__init__.py
> Bump to v51

- recipes/getting-started/getting_started-classification.ipynb
> Fix typos and use kili vocabulary

- kili/__init__.py
> Bump to version 2.52.0

- kili/__init__.py
> Bump version to 2.53

- kili/__init__.py
> Bump to version 2.55.0

- kili/helpers.py
- kili/queries/asset/__init__.py
- kili/types.py
> AAU, on dataset, when I filter on asset metadata, I see a success

- recipes/getting-started/getting_started-image_bounding_box_detection.ipynb
> FIX AA KD, on /docs, in "Getting started", I see a tutorial on "Image bounding-box detection

- kili/__init__.py
> Bump to v56

- kili/__init__.py
> Bump version to 2.57.0

- recipes/OCR_pre_annotations.ipynb
> Google Cloud Vision API

- kili/types.py
> Add new fields for thumbnails

- kili/__init__.py
> Bump to v59

- kili/__init__.py
> Bump to v60

- recipes/OCR_pre_annotations.ipynb
> Fix typo in OCR recipe

- kili/__init__.py
> Bump to v2.61.0

- kili/queries/asset/__init__.py
> Use idIn instead of several id queries

- kili/authentication.py
- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
- kili/mutations/project/__init__.py
- kili/playground.py
- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/user/__init__.py
> AAU, on Python API documentation, I don't see `playground.` but `kili.`

- kili/__init__.py
> Bump to version v62

- kili/__init__.py
> Bump to v2.63.0

- kili/__init__.py
> bump to 2.64.0

- kili/client.py
- kili/playground.py
- kili/queries/issue/__init__.py
- kili/queries/issue/queries.py
- kili/types.py
> Add issue resolvers

- kili/__init__.py
> Bump to version 2.65

- kili/__init__.py
> Bump to version 2.66

- kili/__init__.py
> Bump to version 2.67.0

- kili/__init__.py
> Bump to version 2.68.0

- kili/mutations/project/__init__.py
- kili/mutations/user/__init__.py
- recipes/create_project.ipynb
> AA Admin user, on /members, when I click on "Role in project", I see the role "Reader" doesn't exist anymore

- .travis.yml
- recipes/import_assets.ipynb
- recipes/inference_labels.ipynb
> AAU, on the Kili doc, I see Inference documentation

- kili/authentication.py
Reverts kili-technology/kili-playground#375
> Revert "AAU, on Datadog, when I look at indexed logs, I see a the invoicing d…"

- kili/client.py
- kili/mutations/dataset_asset/__init__.py
- kili/mutations/dataset_asset/fragments.py
- kili/mutations/dataset_asset/queries.py
- kili/playground.py
- kili/queries/dataset_asset/__init__.py
- kili/queries/dataset_asset/queries.py
- kili/types.py
> AAU, on /dataset/addasset, when I upload a local video, I see a success

- kili/__init__.py
> Bump-version-2.71.0

- kili/__init__.py
> Bump version to 2.70

- kili/__init__.py
> Bump version to 2.70.1

- kili/mutations/project/__init__.py
- kili/mutations/user/__init__.py
> Update playground doc

- kili/__init__.py
> bump to version 2.71

- kili/__init__.py
- [] I opened a merge request on `kili` on a branch with the same name than the branch of the current pull request and forced security tests
> bump to version 2.71.1

- kili/__init__.py
> bump to version 2.72

- kili/mutations/label/__init__.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
> AADS, on API, when I set an honeypot on my dataset, I see a success

- kili/__init__.py
> Bump version 2.73

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/queries/lock/__init__.py
> AAU, on API, when I use delete_project, I see a SUCCESS

- kili/__init__.py
> Bump to v2.74.0

- kili/orm.py
- kili/types.py
> Add latest to annotationFormat

- kili/types.py
> Add latest label to kili/types

- kili/orm.py
> Fix airflow export project

- kili/__init__.py
> Bump to 2.75.0

- kili/__init__.py
> bump to 2.77.0

- setup.py
> Fix version of pandas to avoid bug on pandas 1.3.1/1.3.0

- kili/__init__.py
> Bump version to 2.79.0

- kili/graphql_client.py
> Reset reconnection attempt counter if client reconnect

- kili/__init__.py
> Bump to version 2.80.0

- kili/helpers.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/types.py
> Add rules modification to update_properties_in_project

- kili/__init__.py
> Bump version to 2.81.0

- recipes/OCR_pre_annotations.ipynb
- recipes/getting-started/getting_started-image_bounding_box_detection.ipynb
- recipes/getting-started/getting_started-image_classification.ipynb
- recipes/getting-started/getting_started-image_semantic_segmentation.ipynb
- recipes/getting-started/getting_started-named-entity-recognition.ipynb
- recipes/import_text_assets.ipynb
- recipes/pixel_level_masks.ipynb
> Migrate to docusaurus 2.0

- kili/__init__.py
> Bump to 2.82

- kili/__init__.py
> bump version to 2.83

- kili/__init__.py
> bump to version 2.84

- kili/__init__.py
> Bump to 2.85

- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
> Secure mutations for "asset"

- kili/__init__.py
> Bump to 2.86

- kili/queries/asset/__init__.py
- kili/types.py
> AADS, when I request assets of dataset assets, I see a success

- kili/__init__.py
- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
- kili/queries/asset/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/organization/queries.py
- kili/types.py
> Version v2.86.1

- kili/mutations/asset/queries.py
- kili/mutations/dataset/__init__.py
- kili/mutations/dataset/queries.py
- kili/mutations/dataset_asset/__init__.py
- kili/mutations/dataset_asset/queries.py
- kili/mutations/label/__init__.py
- kili/mutations/label/queries.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/mutations/user/__init__.py
- kili/mutations/user/queries.py
- recipes/conf/new_project.yml
> New mutation pattern

- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
- kili/queries/asset/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/organization/queries.py
- kili/types.py
> Revert reverted PR

- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
- kili/mutations/dataset/__init__.py
- kili/mutations/dataset/queries.py
- kili/mutations/label/__init__.py
- kili/mutations/label/queries.py
- kili/mutations/organization/__init__.py
- kili/mutations/organization/queries.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/mutations/user/__init__.py
- kili/mutations/user/queries.py
> Replicate `data` pattern everywhere

- kili/queries/asset/__init__.py
- kili/types.py
> Add missing resolver to playground

- kili/types.py
> Simplify queries for list of projects

- kili/__init__.py
> Bump to version 2.89.0

- kili/__init__.py
> Bump to 2.90

- kili/orm.py
> Add ability to specify label format for latest label

- kili/__init__.py
> Bump to 2.92.0

- kili/__init__.py
> Bump to v2.98

- kili/authentication.py
- kili/client.py
- kili/queries/api_key/__init__.py
- kili/queries/api_key/queries.py
- kili/types.py
> AAU, on Kili, when I create an API key, I see it expires after 1 year

- kili/mutations/organization/__init__.py
- kili/types.py
> Implements canSeeDataset

- kili/__init__.py
> bump to 2.99.0

- recipes/import_predictions.ipynb
> Fix recipe import predictions

- kili/mutations/organization/queries.py
> Fix graphql query

- kili/__init__.py
> Update the kili playground bump version

- kili/__init__.py
> Bump to Kili 2.101

- kili/__init__.py
> Bump to Kili 2.102.0

- recipes/add_users.py
- recipes/conf/new_users.yml
- recipes/create_project.ipynb
- recipes/delete_all_assets.py
> AADS, on Playground, when I run the recipe, I see a success

- .github/workflows/ci.yml
- kili/mutations/asset/__init__.py
- kili/mutations/asset/helpers.py
- kili/mutations/asset/queries.py
- test/mutations/interface.json
- test/mutations/test_asset.py
> AADS, I can upload native videos with the playground

- kili/mutations/asset/helpers.py
- test/mutations/test_asset.py
> Don't probe frame rate for frame video upload

- kili/queries/dataset_asset/__init__.py
- requirements.txt
> Remove fixed version of pandas

- kili/mutations/asset/helpers.py
> Bypass appendManyFrames when frames are already computed

- kili/__init__.py
> Bump to 2.102.1 (due to shift in release versions)

- setup.py
> Don't ask for specific version of pandas

- kili/__init__.py
> Bump version for patching pandas slow install

- kili/__init__.py
> Bump to version 2.103.0

- kili/mutations/project/__init__.py
- kili/mutations/project/fragments.py
- kili/mutations/project/queries.py
> Fix delete project and make project public in the playground

- recipes/getting-started/getting_started-image_bounding_box_detection.ipynb
- recipes/getting-started/getting_started-image_classification.ipynb
- recipes/getting-started/getting_started-image_semantic_segmentation.ipynb
- recipes/getting-started/getting_started-named-entity-recognition.ipynb
- recipes/webhooks.ipynb
> AAU, in Docs, I don't follow broken links

- kili/mutations/user/__init__.py
- kili/mutations/user/queries.py
- kili/queries/user/__init__.py
- kili/types.py
- pull_request_template.md
- recipes/add_users.py
- recipes/conf/new_users.yml
> AA API U, on python client & nodejs client I see field name at user level is deprecated

- kili/__init__.py
> update version of the playground.

- kili/mutations/asset/__init__.py
- kili/types.py
> Add ability to fetch ocr content

- README.md
> README: fix classification task link

- kili/__init__.py
> bump version to 2.105.0

- kili/queries/label/__init__.py
- recipes/frame_dicom_data.ipynb
> AA DS, when I use export_labels_as_df, I see a success

- recipes/frame_dicom_data.ipynb
> fix(LAB-931): revert pipeline fail

- recipes/frame_dicom_data.ipynb
> Hot fix: repair frame-dicom-data notebook

- .github/workflows/ci.yml
> AAKD, add a logger to test_notebooks in the playground

- recipes/README.md
- recipes/google_ner_pre_labeling.py
This PR updates the `recipes/google_ner_pre_labeling.py` to use the up-to-date kili api. It also add a number of features like:
* batch import of assets and predictions.
* creation of the project from scratch to better control the named entity types.
* removal of the asset prioritization (I can put it back if needed)
* formatting / clean-up
> recipes/google_ner_pre_labeling: fix by adapting to up-to-date Kili api

- kili/__init__.py
> bump to 2.106.0

- recipes/frame_dicom_data.ipynb
> fix(LAB-1031): semantic value for tool forbidden for Frame Type

- kili/mutations/asset/helpers.py
- test/mutations/test_asset.py
> feat(LAB-1067): allow to directly import tiff files from the API

- kili/authentication.py
- kili/queries/user/queries.py
> fix(COR-1340): do not fetch all users on authentification for playground

- kili/orm.py
> chore(COR-1021): change yolo_v4_pytorch to yolo_v4

- kili/orm.py
> feat(COR-1347): add YoloV5 format

- kili/types.py
> feat(COR-1418): add new column to playground

- README.md
> fix: Remove link to missing recipe

- kili/constants.py
- kili/helpers.py
- kili/mutations/asset/helpers.py
- test/mutations/test_asset.py
> feat(COR-1354): add check of mime type on uploading assets to project

- kili/__init__.py
> chore: bump release 2.108

- kili/utils.py
- test/queries/test_asset.py
- test/utils.py
> AADS, on Playground, when I query more than 25.000 assets, I am not limited by the API throttling

- kili/types.py
> feat: add latestLabelCompute to playground

- kili/mutations/asset/helpers.py
> AAU, on kili-playground when uploading assets to time series project, I can only upload CSV files and not any text

- kili/authentication.py
- kili/helpers.py
- kili/queries/api_key/__init__.py
- kili/queries/asset/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/label/__init__.py
- kili/queries/lock/__init__.py
- kili/queries/notification/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/project_version/__init__.py
- kili/queries/user/__init__.py
- kili/utils.py
- test/test_utils.py
> AADS, on Playground, when I fetch any object list, there is no limitation and can be output as a generator

- kili/mutations/asset/__init__.py
- kili/mutations/label/__init__.py
- kili/mutations/project/__init__.py
- kili/mutations/user/__init__.py
- kili/queries/api_key/__init__.py
- kili/queries/asset/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/label/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/user/__init__.py
Rephrasing some items in English. No breaking changes. From my perspective, no tests required.
> chore(doc-52)-fixing-some-English-in-py-API

- README.md
Per https://github.com/kili-technology/kili-playground/pull/535
> Removing AutoML

- kili/authentication.py
- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
- kili/queries/label/__init__.py
- kili/queries/project/__init__.py
- kili/types.py
- recipes/conf/new_project.yml
- recipes/query_methods.ipynb
> AAKD, I see no reference to interfaceCategory in the codebase

- kili/__init__.py
> Bump to version 2.111.0

- kili/__init__.py
> [HOTFIX] Bump to version 2.111.1

- recipes/frame_dicom_data.ipynb
> upload dicom asset on bucket

- kili/queries/project/__init__.py
> AAU, when I search a project I just created, it does not appear in the search result (deprecation warning for project field titleAndDescription)

- kili/graphql_client.py
> remove X-powered-By from graphQL queries

- kili/helpers.py
- kili/queries/project/__init__.py
- test/test_deprecation.py
> AAKD, on Python SDK, when want to deprecate arguments, I have the appropriate tooling

- .gitignore
- kili/constants.py
- kili/helpers.py
- kili/mutations/asset/__init__.py
- kili/mutations/asset/helpers.py
- kili/mutations/label/__init__.py
- kili/queries/api_key/__init__.py
- kili/queries/asset/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/label/__init__.py
- kili/queries/lock/__init__.py
- kili/queries/notification/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/project_version/__init__.py
- kili/queries/user/__init__.py
- kili/utils.py
- kili/utils/pagination.py
- test/mutations/test_asset.py
- test/test_utils.py
> AAU, on the SDK, when I mutate more than 100 objects, I see paginated calls

- kili/queries/project/__init__.py
- kili/types.py
- recipes/export_labels.ipynb
- recipes/query_methods.ipynb
> Bump to version 2.112.0 correction

- kili/queries/project/__init__.py
- kili/types.py
- recipes/query_methods.ipynb
> AAKD, I don't see the column titleAndDescription anymore in our database codebase

- README.md
- kili/authentication.py
- kili/queries/asset/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/label/__init__.py
- kili/queries/notification/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_version/__init__.py
> AAU, on the SDK doc, when I look at links, I see that they are up to date

- kili/helpers.py
- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
- requirements.txt
- setup.py
- test/test_search_query.py
> AAKD, on kili-playground, when I look at the API, I want that jsonResponseContains is not used

- kili/__init__.py
> bump to 2.113.0

- .github/workflows/ci.yml
- kili/cli.py
- requirements.txt
- setup.py
> AAU, on the CLI, when I type help or version, I see a success

- .github/workflows/ci.yml
- kili/client.py
- kili/exceptions.py
- kili/helpers.py
- kili/project/__init__.py
- kili/utils/pagination.py
- requirements_dev.txt
- test/fixtures/object_detection_project_fixture.json
- test/test_client_project.py
…e client. Move exceptions in a specific file
> AAU, on the SDK, when I call kili.get_project, I instantiate a project object with high level methods

- docs/lock.md
- mkdocs.yml
> AAU, on the SDK reference doc, when I look at the methods, I don't see the locks

- README.md
> fix: remove dead link

- kili/cli.py
- requirements.txt
- setup.py
- test/test_cli.py
> AAU, on the CLI I see a function to list all projects with minimum information

- kili/__init__.py
> release: bump to 2.114

- docs/cli_getting_started.md
- docs/cli_reference.md
- docs/index.md
- kili/cli.py
- mkdocs.yml
> AAU, on the SDK reference website, when I look for the CLI documentation, I see a success

- kili/queries/asset/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/label/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/project_version/__init__.py
- recipes/import_assets.ipynb
- recipes/inference_labels.ipynb
- test/queries/test_asset.py
- test/queries/test_label.py
> chore: make project_id mandatory in queries

- kili/cli.py
> AAU, on the CLI, when I do kili project list, I don't see the progress bar

- kili/graphql_client.py
> feat(CORE-1840): do no retry 401 requests

- kili/cli.py
- kili/queries/project/helpers.py
```
$kili project create --interface project.txt --title "ThE TeSt PrOjEct 2" --input-type TEXT                                  
PROJECT ID                 URL
cl4ybma5801980mwg9uz59wqr  https://cloud.kili-technology.com/label/projects/cl4ybma5801980mwg9uz59wqr/
```
```
$kili project list
TITLE                                               ID                           PROGRESS  DESCRIPTION
ThE TeSt PrOjEct 4                                  cl4ybma5801980mwg9uz59wqr         nan
ThE TeSt PrOjEct 3                                  cl4ybixbm00p60ly66x494m5e         nan
ThE TeSt PrOjEct 2                                  cl4ybg5ea009v0ly6d9hj22s2         nan
CoNLL Named Entity Recognition                      cl4ww6rwz1eya0lwj1dd4801f       50.0%  Find named entities in CoNLL 2003
For more …
```
> feat(ML-499): improved project creation fmt

- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
- kili/orm.py
> AAU, on the SDK, when I call kili.add_assets_to_review(...), I want to add these assets to review

- kili/cli.py
- kili/queries/project/helpers.py
- test/test_cli.py
and also fix all cli typing errors.
```
$ kili project describe ckyctp1bl006h0m0y0djm5jur                                                
Title        Test5 - PDF classification
Description  PDF classification
URL          https://cloud.kili-technology.com/label/projects/ckyctp1bl006h0m0y0djm5jur/
Dataset KPIs
------------
Total number of assets      2
Number of remaining assets  1
Skipped assets              0
Progress                    50.0%
Quality KPIs
------------
Project consensus           N/A
Project honeypot            N/A
Number of reviewed assets   0
Number of open issues       0
Number of solved issues     0
Number of open questions    0
Number of solved questions  0
```
> feat(ML-519): add project URL

- kili/cli.py
- kili/client.py
- kili/queries/project/helpers.py
- recipes/get_labeler_stats.py
- recipes/set_asset_to_be_labeled_by.py
- recipes/update_project_instructions.py
- recipes/update_project_title.py
- test/mutations/test_asset.py
- test/test_cli.py
> AAU, on the CLI, I see a better management of the environnement variables

- kili/queries/api_key/__init__.py
- kili/queries/issue/__init__.py
- kili/queries/lock/__init__.py
- kili/queries/notification/__init__.py
- kili/queries/organization/__init__.py
- kili/queries/project/__init__.py
- kili/queries/project_user/__init__.py
- kili/queries/project_version/__init__.py
- kili/queries/user/__init__.py
> fix(ML-226): first None by default

- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
> fix: deprecation message error

- kili/queries/asset/__init__.py
- kili/queries/label/__init__.py
> chore: remove json response contains

- kili/cli.py
- kili/constants.py
- kili/mutations/asset/__init__.py
- kili/mutations/asset/helpers.py
- kili/mutations/project/__init__.py
- test/test_cli.py
> feat(LAB-1589): revert until the next MEP

- kili/mutations/asset/__init__.py
- kili/mutations/asset/queries.py
> AAU, on the SDK, when I call kili.send_back_to_queue(..., I want to send assets back to queue

- kili/mutations/project/__init__.py
- kili/mutations/project/queries.py
> AA DS U, on kili python sdk, I see I can import metadata as range

- .github/workflows/ci.yml
- .github/workflows/daily.yml
> chore: separate notebook tests and run on weekdays

- kili/cli/project/member/__init__.py
- kili/cli/project/member/add.py
- kili/cli/project/member/helpers.py
- kili/cli/project/member/list_.py
- test/cli/test_project.py
Follow https://github.com/kili-technology/kili-python-sdk/pull/614
> AAU, on the CLI, I see a function to add member(s) to a project

- kili/__init__.py
- kili/authentication.py
- kili/cli/helpers.py
- kili/cli/project/__init__.py
- kili/cli/project/export.py
- kili/project/__init__.py
- kili/services/__init__.py
- kili/services/export/exceptions.py
- kili/services/export/format/base.py
- kili/services/export/format/yolo/__init__.py
- kili/services/export/format/yolo/common.py
- kili/services/export/format/yolo/merge.py
- kili/services/export/format/yolo/split.py
- kili/services/export/repository.py
- kili/services/export/tools.py
- kili/services/export/typing.py
- recipes/ocr_pre_annotations.ipynb
- setup.cfg
- test/cli/test_project.py
- test/services/export/expected/classes.txt
- test/services/export/expected/data.yaml
- test/services/export/fakes/fake_content_repository.py
- test/services/export/fakes/fake_data.py
- test/services/export/fakes/fake_kili.py
- test/services/export/test_export.py
- Revert "Revert "feat: add yolo export (#655)" (#662)"
- fix: missing init file
- chore: restore version to 2.119.1
We will launch the bump script and the release once merged.
> fix and restore version to 2.119.1

- kili/utils/bucket.py
- kili/utils/tqdm.py
- fix: fix signed_urls request
- fix: tqdm used
> FIX tqdm and Frame import

- kili/types.py
- A merge request on Gitlab also exists
> AA Kili Admin User, I can access the whole license

- kili/cli/project/label.py
- kili/services/label_import/__init__.py
- test/services/import_labels/test_cases.py
- test/services/import_labels/test_import.py
yolo v7 import was not possible. Fixed and added a test
> fix: missing yolo v7 import case

- .github/workflows/pr.yml
> chore: check that the PR title respects commit conventions

- .pylintrc
- setup.py
- src/kili/authentication.py
- src/kili/graphql_client.py
- src/kili/helpers.py
- src/kili/mutations/issue/helpers.py
- src/kili/services/export/repository.py
- src/kili/utils/bucket.py
- build: remove pylint version blocking
- style: remove the pylint obsolete errors
> build: remove pylint version blocking

- src/kili/graphql/operations/plugins/fragments.py
- src/kili/graphql/operations/plugins/queries.py
- src/kili/mutations/plugins/__init__.py
- src/kili/services/plugins/__init__.py
- src/kili/services/plugins/logs.py
- src/kili/utils/bucket.py
> feat: 🎸 Add get logs plugin

- entrypoint.sh
I removed the pull from master since I did not get why it was useful after all.
> build: remove pulling from master

- src/kili/cli/project/export.py
- src/kili/cli/project/label.py
- src/kili/services/export/__init__.py
- src/kili/services/export/format/base.py
- src/kili/services/export/types.py
- src/kili/services/label_import/__init__.py
- src/kili/services/label_import/types.py
> feat: add kili export and import type

- src/kili/services/export/__init__.py
- src/kili/services/export/format/base.py
- refac: remove dead code
- refac: remove useless root init
- refac: remove need to instanciate kili
> refactor(export): remove some dead code

- setup.cfg
- src/kili/__init__.py
Activate plugins manager in prod
> feat: 2.125.0 → 2.125.1

- src/kili/mutations/project/__init__.py
- src/kili/mutations/project/queries.py
Resolves [AADS, on sdk, when I call archive_project, I see the project archived](https://linear.app/kili-technology/issue/COM-412/aads-on-sdk-when-i-call-archive-project-i-see-the-project-archived)
> feat(com-412): AADS, on sdk, when I call archive_project, I see the project archived

- src/kili/services/plugins/tools.py
> feat: 🎸 update hint message when plugin is already uploaded

- recipes/basic_project_setup.ipynb
Co-authored-by: Przemysław Czuba <Przemyslaw.czuba@kili-technology.com>
> docs: add notebook to create users

- .github/workflows/e2e_tests.yml
- recipes/frame_dicom_data.ipynb
- recipes/medical_imaging.ipynb
CI: https://github.com/kili-technology/kili-python-sdk/actions/runs/3622045124
> test: remove platform specific e2e tests

- .github/workflows/release.yml
- entrypoint.sh
CI: https://github.com/kili-technology/kili-python-sdk/actions/runs/3646440104/jobs/6157525891
Created branch: https://github.com/kili-technology/kili-python-sdk/tree/release/2.127.0
remember to delete release/2.127.0 branch after merging
> ci: create minor release branch workflow

- docs/sdk/project_user.md
- src/kili/client.py
- src/kili/mutations/project/__init__.py
- src/kili/mutations/project/queries.py
- src/kili/mutations/project_user/__init__.py
> refactor: move project_user mutations

- src/kili/mutations/project/__init__.py
- fix: none is an acceptable value type
> fix: none is an acceptable value type

- src/kili/exceptions.py
- tests/test_helpers.py
`pytest --cov kili.helpers --cov-report term-missing tests/test_helpers.py`
> test: add tests for format_result

- docs/sdk/tutorials/export_a_kili_project.md
Following discussions with Damien
> docs: add latest label per user

- src/kili/cli/project/export.py
https://python-sdk-docs.kili-technology.com/2.126/cli/reference/#export
> docs: fix indentation

- src/kili/services/plugins/activation.py
- src/kili/services/plugins/tools.py
> feat: 🎸 show hint when plugin was already activated

- src/kili/mutations/asset/__init__.py
- src/kili/mutations/project/__init__.py
- src/kili/queries/asset/__init__.py
- tests/e2e/test_mutations_asset.py
- tests/e2e/test_mutations_project.py
@xczuba Please checkout that branch and run your notebook on it, in order to make sure the outputs are good for the tutorials
Modified methods:
- add_to_review
- send_back_to_queue
- update_properties_in_project
> feat: add more information in mutation return values

- .github/workflows/e2e_tests.yml
- src/kili/queries/asset/__init__.py
- src/kili/queries/asset/helpers.py
- tests/e2e/test_query_assets_download_media.py
e2e tests: https://github.com/kili-technology/kili-python-sdk/actions/runs/3854143052
notebook tests take longer to finish, so better run them last
> fix: fix import for tests

- src/kili/services/export/format/base.py
- src/kili/services/export/format/coco/__init__.py
- tests/services/export/test_coco.py
add rectangle as compatible tool for coco exports
> fix: fix bug in coco export

- tests/e2e/paginated_calls_project_lifecycle.ipynb
- tests/test_notebooks.py
I removed the notebook from the release Kili functional testing template
> feat: add release notebook to end to end tests

- src/kili/services/plugins/activation.py
- src/kili/services/plugins/tools.py
> feat: 🎸 do not throw error if plugin already activated

- src/kili/services/copy_project/__init__.py
- src/kili/types.py
stop copy if project has a remote storage
> fix: disable copy project for assets on remote storage

- docs/sdk/tutorials/plugins_development.md
- recipes/plugins_development.ipynb
- src/kili/services/plugins/model.py
> feat: 🎸 add part for multi-file plugin in notebook

- src/kili/mutations/asset/__init__.py
- src/kili/services/asset_import/base.py
- src/kili/services/asset_import/exceptions.py
- src/kili/services/asset_import/image.py
- src/kili/services/asset_import/pdf.py
- src/kili/services/asset_import/text.py
- src/kili/services/asset_import/video.py
- tests/services/asset_import/mocks.py
- tests/services/asset_import/test_import_common.py
- tests/services/asset_import/test_import_image.py
- tests/services/asset_import/test_import_pdf.py
- tests/services/asset_import/test_import_text.py
- tests/services/asset_import/test_import_video.py
> fix: data should not be imported if the license does not allow it (#966)

- src/kili/queries/asset/__init__.py
- src/kili/queries/asset/media_downloader.py
- src/kili/services/copy_project/__init__.py
- src/kili/services/export/tools.py
> fix: fix bugs in ProjectCopier and MediaDownloader

- tests/e2e/test_copy_project.py
fixes: https://github.com/kili-technology/kili-python-sdk/actions/runs/4104926390/jobs/7081080027
e2e tests: https://github.com/kili-technology/kili-python-sdk/actions/runs/4105364152
> test: fix copy project e2e tests

- src/kili/helpers.py
- src/kili/mutations/asset/__init__.py
- src/kili/mutations/project/__init__.py
- src/kili/queries/asset/media_downloader.py
- src/kili/services/asset_import/__init__.py
- src/kili/services/asset_import/base.py
- src/kili/utils/bucket.py
- tests/e2e/test_query_assets_download_media.py
- tests/services/asset_import/base.py
- tests/services/asset_import/test_import_common.py
- tests/services/asset_import/test_import_image.py
- tests/services/asset_import/test_import_pdf.py
- tests/services/asset_import/test_import_text.py
- tests/test_helpers.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4133821802
still one plugin notebook failing
> feat: add `wait_until_availability` argument for `append_many_to_dataset`

- docs/sdk/plugins.md
> docs: ✏️ adapt plugins documentation to module type plugins

- docs/sdk/tutorials/basic_project_setup.md
- docs/sdk/tutorials/plugins_development.md
- docs/sdk/tutorials/plugins_example.md
- recipes/basic_project_setup.ipynb
- recipes/plugins_development.ipynb
- recipes/plugins_example.ipynb
- src/kili/exceptions.py
- src/kili/graphql/graphql_client.py
- src/kili/utils/pagination.py
- tests/e2e/test_graphql_client.py
- tests/e2e/test_json_response_validation.py
e2e pass: https://github.com/kili-technology/kili-python-sdk/actions/runs/4280730417
> refactor: revert old GraphQLError exception

- docs/sdk/plugins.md
- src/kili/services/plugins/model.py
> docs: ✏️ Detail the fields available for label in plugin handler

- src/kili/services/plugins/model.py
> docs: ✏️ add reviewedLabel to on_review docstring of plugins

- src/kili/cli/project/export.py
- src/kili/project/__init__.py
- src/kili/queries/label/__init__.py
- src/kili/services/export/__init__.py
- src/kili/services/export/format/base.py
- src/kili/services/export/format/coco/__init__.py
- src/kili/services/export/format/coco/types.py
- src/kili/services/export/types.py
- tests/services/export/helpers/coco.py
- tests/services/export/test_coco.py
- tests/services/export/test_export.py
> feat: add ability to add an annotation modifier to COCO exports (#1055)

- .coveragerc
- src/kili/enums.py
- src/kili/types.py
fix #1086, already merged to master
> fix: reintroduce types and enums to avoid breaking changes (#1086)

- src/kili/queries/asset/media_downloader.py
- src/kili/services/copy_project/__init__.py
- tests/e2e/test_copy_project.py
- tests/e2e/test_query_assets_download_media.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/4532521658
> fix: add ocrmetadata to project copier

- src/kili/services/asset_import/base.py
> feat: add warning message when assets are filtered because of duplicate external ids

- setup.py
https://github.com/kili-technology/kili-python-sdk/actions/runs/4894248469/jobs/8738242891
> build: lock urllib major version

- .github/workflows/e2e_tests.yml
- tests/test_notebooks.py
https://github.com/kili-technology/kili-python-sdk/actions/runs/5143131656
PYDEVD_DISABLE_FILE_VALIDATION disable these errors:
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
> ci: e2e on python 3.11

- src/kili/client.py
- src/kili/core/authentication.py
- src/kili/core/graphql/graphql_client.py
- tests/test_client.py
https://github.com/kili-technology/kili-python-sdk/actions/runs/5224355458
> feat: add graphql_client_params arg to Kili client

- src/kili/core/graphql/graphql_client.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/5347024792
> fix: add retries when gql gets 401 server errors

- tests/e2e/test_cloud_storage.py
test the sync cloud storage on preprod data integrations
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/5345552614
> test:  update data integrations sync cloud storage e2e test

- src/kili/entrypoints/mutations/asset/__init__.py
- src/kili/entrypoints/mutations/asset/helpers.py
- tests/integration/entrypoints/mutations/test_assets.py
e2e: https://github.com/kili-technology/kili-python-sdk/actions/runs/5445053874
> refactor: more typing for the property processing

- src/kili/entrypoints/mutations/project/__init__.py
- tests/e2e/test_projects.py
remove the retries if not needed
> fix: wait for project to be archived in `archive_project`

- .github/workflows/ci.yml
- tests/e2e/test_client.py
- tests/e2e/test_cloud_storage.py
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions <github-actions@github.com>
> test: update kili client init test

- src/kili/entrypoints/mutations/label/__init__.py
- src/kili/entrypoints/mutations/label/queries.py
- tests/e2e/test_mutations_label.py
- tests/integration/entrypoints/mutations/test_labels.py
to merge when the MR on kili staging is merged
> feat: add `kili.delete_labels()`

- src/kili/client.py
I was spammed with those warnings when adding assets to a kili project:
```
ARNING:urllib3.connectionpool:Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.64it/s]
0%|                                                                                                                                                       | 0/11 [00:01<?, ?it/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: storage.googleapis.com. …
```
> fix: disable urllib3 warnings related to connection pool

- docs/sdk/tutorials/set_up_workflows.md
- recipes/set_up_workflows.ipynb
Co-authored-by: github-actions <github-actions@github.com>
>  docs: fix notebook setup workflow 

- docs/sdk/tutorials/basic_project_setup.md
- docs/sdk/tutorials/importing_assets_and_metadata.md
- docs/sdk/tutorials/importing_labels.md
- recipes/basic_project_setup.ipynb
- recipes/importing_assets_and_metadata.ipynb
- recipes/importing_labels.ipynb
- recipes/set_up_workflows.ipynb
- tests/e2e/test_query_assets_by_external_id.py
- tests/e2e/test_text_encoding_consistency.py
- tests/unit/services/label_data_parsing/mutation/test_mutation_exceptions.py
See Linear for details, to be short an error on tutorials that prevented to use the filters
> fix: missing key in json interfaces

- .github/workflows/ci.yml
- .github/workflows/publish.yml
staging is not always up when we push commits at 5am  🙃
> ci: fix test build step

- src/kili/core/graphql/operations/label/queries.py
- src/kili/entrypoints/queries/label/__init__.py
- tests/e2e/test_query_labels.py
need to wait for the fix backend side to merge this MR
> fix: fix label query with asset externalid filters

- .github/workflows/ci.yml
- docs/sdk/issue.md
- docs/sdk/project.md
- src/kili/entrypoints/mutations/asset/__init__.py
> fix: min max zoom arg doc and doc building

- src/kili/services/copy_project/__init__.py
- src/kili/services/export/format/base.py
- src/kili/use_cases/asset/media_downloader.py
- tests/e2e/test_notebooks.py
- tests/fakes/fake_kili.py
- tests/integration/use_cases/test_asset.py
- tests/unit/services/export/test_coco.py
- tests/unit/services/export/test_export.py
- tests/unit/services/export/test_geojson.py
- tests/unit/services/export/test_kili.py
- tests/unit/services/export/test_voc.py
- tests/unit/services/export/test_yolo.py
the dataConnections resolver requires paid license and admin role, but not the projects resolver... 🤔
> fix: use projects resolver to check for data connections

- .github/workflows/publish.yml
Reverts kili-technology/kili-python-sdk#1568
> revert: add changelog in slack publish message

- src/kili/core/graphql/graphql_client.py
fix for: https://github.com/kili-technology/kili-python-sdk/actions/runs/6953940786/job/18919892795
> fix: add retries in graphql client for TransportServerError

- src/kili/core/constants.py
> feat(lab-2558): allow to import jp2 and nitf images

- src/kili/adapters/kili_api_gateway/asset/operations_mixin.py
- src/kili/adapters/kili_api_gateway/label/annotation_to_json_response.py
- src/kili/core/graphql/graphql_client.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_15.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_16.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_17.py
- tests/unit/adapters/kili_api_gateway/label/test_label_utils.py
- tests/unit/test_graphql_client.py
> fix(SUP-1444): bug in annotation export json file

- src/kili/entrypoints/mutations/asset/__init__.py
- src/kili/services/asset_import/__init__.py
- src/kili/services/asset_import/base.py
- src/kili/services/asset_import/image.py
- src/kili/services/asset_import/text.py
- src/kili/services/asset_import/types.py
- tests/unit/services/asset_import/base.py
- tests/unit/services/asset_import/test_import_image.py
This PR should be merged after https://gitlab.com/kili-technology/kili/-/merge_requests/11663
> feat(lab-2753): add support for multilayer

- src/kili/adapters/kili_api_gateway/asset/mappers.py
- src/kili/adapters/kili_api_gateway/label/annotation_to_json_response.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_12.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_18.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_19.py
- tests/unit/adapters/kili_api_gateway/label/test_data/test_case_6.py
- tests/unit/adapters/kili_api_gateway/label/test_label_utils.py
Ensure SDK includes nested jobs in the json response
> feat(LAB-2816): AAU, I can use nested jobs in the LLM interface

- src/kili/adapters/kili_api_gateway/asset/operations.py
- src/kili/adapters/kili_api_gateway/asset/operations_mixin.py
- src/kili/services/asset_import/base.py
Speed up upload of new assets for project with many assets
> feat: use a dedicated endpoint to check if external ids are in a project

- pyproject.toml
- src/kili/entrypoints/cli/project/create.py
- src/kili/entrypoints/cli/project/describe.py
- src/kili/entrypoints/cli/project/list_.py
- src/kili/entrypoints/cli/project/member/list_.py
- src/kili/services/asset_import/image.py
- src/kili/services/export/format/coco/__init__.py
- src/kili/services/export/format/kili/__init__.py
- src/kili/services/export/format/voc/__init__.py
- src/kili/services/export/format/yolo/__init__.py
- src/kili/services/label_import/importer/__init__.py
- src/kili/use_cases/label/process_shapefiles.py
- tests/unit/services/export/test_coco.py
Needs https://github.com/kili-technology/kili-formats/pull/9 before merging this
> chore(lab-3743): refine dependencies and make some optional

- src/kili/presentation/client/project.py
MR to clarify metadata properties for project
> docs: update metadata properties documentation
